// SPDX-License-Identifier: GPL-3.0-or-later
//
// TorqueBus Studio
// Copyright (C) TorqueBus contributors
//
// The name table we actually ship, parsed by the code that will parse it.
//
// J1939NameTablesTests covers the loader against input written for it. This
// covers the other half, which nothing did: the generated file in `data/` that
// goes into every package. It is generated by a Python script from a source
// this build does not have, so nothing here would notice if a regeneration
// produced a malformed line - not the compiler, not the loader's own tests,
// not the packaging check, which confirms the file is present and says nothing
// about what is in it.
//
// The symptom would be a line in the Output panel at startup, on a machine
// belonging to somebody who downloaded a release.

#include "core/j1939/J1939Name.h"
#include "core/j1939/J1939NameTables.h"

#include "UniqueTempPath.h"

#include <gtest/gtest.h>

#include <filesystem>
#include <fstream>

using namespace torquebus;

namespace {

[[nodiscard]] std::filesystem::path shippedTable()
{
    return std::filesystem::path{TORQUEBUS_DATA_DIR} / "j1939-names-functions.csv";
}

/// A NAME carrying just enough to ask the table a question.
[[nodiscard]] J1939Name
nameWith(std::uint8_t function, std::uint8_t vehicleSystem = 0U, std::uint8_t industryGroup = 0U)
{
    J1939Name name;
    name.function = function;
    name.vehicleSystem = vehicleSystem;
    name.industryGroup = industryGroup;
    return name;
}

} // namespace

TEST(ShippedNameTableTests, TheShippedJ1939FunctionTableIsThereAndParses)
{
    ASSERT_TRUE(std::filesystem::exists(shippedTable()));

    J1939NameTables tables;

    // Not "did it load something" - did it load without complaining. A
    // malformed line is refused with its number, and that refusal is the whole
    // point of this test.
    const Result result = tables.loadFile(shippedTable());
    SCOPED_TRACE(::testing::Message()
                 << "loading " << shippedTable().string() << ": " << result.message());
    ASSERT_TRUE(result.succeeded());

    EXPECT_FALSE(tables.empty());
}

TEST(ShippedNameTableTests, TheShippedTableAnswersTheQuestionsItExistsToAnswer)
{
    J1939NameTables tables;
    ASSERT_TRUE(tables.loadFile(shippedTable()).succeeded());
    {
        // Function 0 is Engine in every industry group, and if this table ever
        // stops saying so then something has gone wrong upstream in a way no
        // count would reveal.
        const auto engine = tables.function(nameWith(0U));
        ASSERT_TRUE(engine.has_value());
        EXPECT_TRUE(*engine == "Engine");

        // A bare number keys the whole 0..127 range, and there are 128 of them
        // at most. Enough of them to be worth shipping is the claim the file's
        // own header makes.
        EXPECT_TRUE(tables.functionCount() > 100U);
    }
    {
        // 1/0/134 is on-highway, vehicle system 0, function 134. Asking for
        // function 134 alone must not answer, because at or above 128 the
        // number means different things in different industry groups; that is
        // the interface promise in J1939NameTables.h and this is the file that
        // has to keep it.
        const auto retarder = tables.function(nameWith(134U, 0U, 1U));
        ASSERT_TRUE(retarder.has_value());
        EXPECT_TRUE(*retarder == "Retarder Display");

        EXPECT_FALSE(tables.function(nameWith(134U, 0U, 0U)).has_value());

        // 1/0/128 is deliberately absent. AgIsoStack has two On-Highway blocks
        // whose headings both read "Non-specific system (Device class 0)", and
        // 128 to 132 appear in each with different names. The converter refuses
        // a key two entries claim, because one of them is wrong and the source
        // does not say which - and the loader would otherwise hand back
        // whichever came last.
        EXPECT_FALSE(tables.function(nameWith(128U, 0U, 1U)).has_value());
    }
    {
        // The manufacturer registry is licensed and is not ours to
        // redistribute. If this ever stops being zero, somebody has put a
        // licensed table into the repository - which .gitignore and the
        // packaging check both try to prevent, and which this would catch on
        // the way in.
        EXPECT_TRUE(tables.manufacturerCount() == 0U);
    }
}

TEST(ShippedNameTableTests, ASecondTableLoadedOnTopOverridesTheShippedOne)
{
    // The mechanism that lets somebody with a licensed Digital Annex correct
    // this file rather than sit beside it. Tested against the real shipped
    // table, because "later entries win" has to hold for the actual keys in it
    // and not only for a synthetic pair.
    J1939NameTables tables;
    ASSERT_TRUE(tables.loadFile(shippedTable()).succeeded());
    ASSERT_TRUE(tables.function(nameWith(0U)) == "Engine");

    // Through a file, because merge(string_view) is private: the public way in
    // is the one a person holding a Digital Annex would actually use.
    const std::filesystem::path theirs =
        torquebus::tests::uniqueTempPath("j1939-override", 1, ".csv");
    {
        std::ofstream out{theirs};
        out << "function,0,Something Else\n";
    }

    const Result merged = tables.mergeFile(theirs);
    std::filesystem::remove(theirs);
    ASSERT_TRUE(merged.succeeded());

    const auto overridden = tables.function(nameWith(0U));
    ASSERT_TRUE(overridden.has_value());
    EXPECT_TRUE(*overridden == "Something Else");

    // And a key the second file did not mention keeps what the first gave it.
    EXPECT_TRUE(tables.function(nameWith(134U, 0U, 1U)) == "Retarder Display");
}
